name: ClickTheButton
version: ${project.version}
main: nl.dizmizzer.ctb.core.ClickTheButton
description: Click The Button Gamemode. Known from Minecraft Monday hosted by keemstar.

commands:
  ctb:
    usage: /<command>
